version: '3.3'
services:
  api:
#    build: .
    image: 'arykalin/kogda-sobitie-backend:1.0.0'
    ports:
      - '8080'
    volumes:
      - .:/app/cmd/server
    depends_on:
      - 'mongo'
  web:
    container_name: 'web'
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - ./scripts/nginx/dev.conf.d:/etc/nginx/conf.d
    depends_on:
      - 'api'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - ./data/dev/mongo:/data/db
