// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GrpcAuthenticateResponse grpc authenticate response
//
// swagger:model grpcAuthenticateResponse
type GrpcAuthenticateResponse struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this grpc authenticate response
func (m *GrpcAuthenticateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GrpcAuthenticateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GrpcAuthenticateResponse) UnmarshalBinary(b []byte) error {
	var res GrpcAuthenticateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
