// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/arykalin/kogda-sobitie-backend/pkg/server/v1/grpc/clients/models"
)

// NewAPIServiceCreateEventParams creates a new APIServiceCreateEventParams object
// with the default values initialized.
func NewAPIServiceCreateEventParams() *APIServiceCreateEventParams {
	var ()
	return &APIServiceCreateEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIServiceCreateEventParamsWithTimeout creates a new APIServiceCreateEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIServiceCreateEventParamsWithTimeout(timeout time.Duration) *APIServiceCreateEventParams {
	var ()
	return &APIServiceCreateEventParams{

		timeout: timeout,
	}
}

// NewAPIServiceCreateEventParamsWithContext creates a new APIServiceCreateEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIServiceCreateEventParamsWithContext(ctx context.Context) *APIServiceCreateEventParams {
	var ()
	return &APIServiceCreateEventParams{

		Context: ctx,
	}
}

// NewAPIServiceCreateEventParamsWithHTTPClient creates a new APIServiceCreateEventParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIServiceCreateEventParamsWithHTTPClient(client *http.Client) *APIServiceCreateEventParams {
	var ()
	return &APIServiceCreateEventParams{
		HTTPClient: client,
	}
}

/*APIServiceCreateEventParams contains all the parameters to send to the API endpoint
for the Api service create event operation typically these are written to a http.Request
*/
type APIServiceCreateEventParams struct {

	/*Body*/
	Body *models.GrpcCreateEventRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api service create event params
func (o *APIServiceCreateEventParams) WithTimeout(timeout time.Duration) *APIServiceCreateEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api service create event params
func (o *APIServiceCreateEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api service create event params
func (o *APIServiceCreateEventParams) WithContext(ctx context.Context) *APIServiceCreateEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api service create event params
func (o *APIServiceCreateEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api service create event params
func (o *APIServiceCreateEventParams) WithHTTPClient(client *http.Client) *APIServiceCreateEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api service create event params
func (o *APIServiceCreateEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the Api service create event params
func (o *APIServiceCreateEventParams) WithBody(body *models.GrpcCreateEventRequest) *APIServiceCreateEventParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the Api service create event params
func (o *APIServiceCreateEventParams) SetBody(body *models.GrpcCreateEventRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *APIServiceCreateEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
