// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/arykalin/kogda-sobitie-backend/pkg/server/v1/grpc/clients/models"
)

// APIServiceUpdateEventReader is a Reader for the APIServiceUpdateEvent structure.
type APIServiceUpdateEventReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIServiceUpdateEventReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAPIServiceUpdateEventOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAPIServiceUpdateEventDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAPIServiceUpdateEventOK creates a APIServiceUpdateEventOK with default headers values
func NewAPIServiceUpdateEventOK() *APIServiceUpdateEventOK {
	return &APIServiceUpdateEventOK{}
}

/*APIServiceUpdateEventOK handles this case with default header values.

A successful response.
*/
type APIServiceUpdateEventOK struct {
	Payload *models.GrpcUpdateEventResponse
}

func (o *APIServiceUpdateEventOK) Error() string {
	return fmt.Sprintf("[PUT /event/{eventId}][%d] apiServiceUpdateEventOK  %+v", 200, o.Payload)
}

func (o *APIServiceUpdateEventOK) GetPayload() *models.GrpcUpdateEventResponse {
	return o.Payload
}

func (o *APIServiceUpdateEventOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcUpdateEventResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIServiceUpdateEventDefault creates a APIServiceUpdateEventDefault with default headers values
func NewAPIServiceUpdateEventDefault(code int) *APIServiceUpdateEventDefault {
	return &APIServiceUpdateEventDefault{
		_statusCode: code,
	}
}

/*APIServiceUpdateEventDefault handles this case with default header values.

An unexpected error response.
*/
type APIServiceUpdateEventDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the Api service update event default response
func (o *APIServiceUpdateEventDefault) Code() int {
	return o._statusCode
}

func (o *APIServiceUpdateEventDefault) Error() string {
	return fmt.Sprintf("[PUT /event/{eventId}][%d] ApiService_UpdateEvent default  %+v", o._statusCode, o.Payload)
}

func (o *APIServiceUpdateEventDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *APIServiceUpdateEventDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
