// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/arykalin/kogda-sobitie-backend/pkg/server/v1/grpc/clients/models"
)

// APIServiceCreateEventReader is a Reader for the APIServiceCreateEvent structure.
type APIServiceCreateEventReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIServiceCreateEventReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAPIServiceCreateEventOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAPIServiceCreateEventDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAPIServiceCreateEventOK creates a APIServiceCreateEventOK with default headers values
func NewAPIServiceCreateEventOK() *APIServiceCreateEventOK {
	return &APIServiceCreateEventOK{}
}

/*APIServiceCreateEventOK handles this case with default header values.

A successful response.
*/
type APIServiceCreateEventOK struct {
	Payload *models.GrpcCreateEventResponse
}

func (o *APIServiceCreateEventOK) Error() string {
	return fmt.Sprintf("[POST /event][%d] apiServiceCreateEventOK  %+v", 200, o.Payload)
}

func (o *APIServiceCreateEventOK) GetPayload() *models.GrpcCreateEventResponse {
	return o.Payload
}

func (o *APIServiceCreateEventOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcCreateEventResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIServiceCreateEventDefault creates a APIServiceCreateEventDefault with default headers values
func NewAPIServiceCreateEventDefault(code int) *APIServiceCreateEventDefault {
	return &APIServiceCreateEventDefault{
		_statusCode: code,
	}
}

/*APIServiceCreateEventDefault handles this case with default header values.

An unexpected error response.
*/
type APIServiceCreateEventDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the Api service create event default response
func (o *APIServiceCreateEventDefault) Code() int {
	return o._statusCode
}

func (o *APIServiceCreateEventDefault) Error() string {
	return fmt.Sprintf("[POST /event][%d] ApiService_CreateEvent default  %+v", o._statusCode, o.Payload)
}

func (o *APIServiceCreateEventDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *APIServiceCreateEventDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
