// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAPIServiceUpdateEventParams creates a new APIServiceUpdateEventParams object
// with the default values initialized.
func NewAPIServiceUpdateEventParams() *APIServiceUpdateEventParams {
	var ()
	return &APIServiceUpdateEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIServiceUpdateEventParamsWithTimeout creates a new APIServiceUpdateEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIServiceUpdateEventParamsWithTimeout(timeout time.Duration) *APIServiceUpdateEventParams {
	var ()
	return &APIServiceUpdateEventParams{

		timeout: timeout,
	}
}

// NewAPIServiceUpdateEventParamsWithContext creates a new APIServiceUpdateEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIServiceUpdateEventParamsWithContext(ctx context.Context) *APIServiceUpdateEventParams {
	var ()
	return &APIServiceUpdateEventParams{

		Context: ctx,
	}
}

// NewAPIServiceUpdateEventParamsWithHTTPClient creates a new APIServiceUpdateEventParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIServiceUpdateEventParamsWithHTTPClient(client *http.Client) *APIServiceUpdateEventParams {
	var ()
	return &APIServiceUpdateEventParams{
		HTTPClient: client,
	}
}

/*APIServiceUpdateEventParams contains all the parameters to send to the API endpoint
for the Api service update event operation typically these are written to a http.Request
*/
type APIServiceUpdateEventParams struct {

	/*EventID*/
	EventID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api service update event params
func (o *APIServiceUpdateEventParams) WithTimeout(timeout time.Duration) *APIServiceUpdateEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api service update event params
func (o *APIServiceUpdateEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api service update event params
func (o *APIServiceUpdateEventParams) WithContext(ctx context.Context) *APIServiceUpdateEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api service update event params
func (o *APIServiceUpdateEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api service update event params
func (o *APIServiceUpdateEventParams) WithHTTPClient(client *http.Client) *APIServiceUpdateEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api service update event params
func (o *APIServiceUpdateEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEventID adds the eventID to the Api service update event params
func (o *APIServiceUpdateEventParams) WithEventID(eventID string) *APIServiceUpdateEventParams {
	o.SetEventID(eventID)
	return o
}

// SetEventID adds the eventId to the Api service update event params
func (o *APIServiceUpdateEventParams) SetEventID(eventID string) {
	o.EventID = eventID
}

// WriteToRequest writes these params to a swagger request
func (o *APIServiceUpdateEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param eventId
	if err := r.SetPathParam("eventId", o.EventID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
