// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAPIServiceAuthenticateParams creates a new APIServiceAuthenticateParams object
// with the default values initialized.
func NewAPIServiceAuthenticateParams() *APIServiceAuthenticateParams {

	return &APIServiceAuthenticateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIServiceAuthenticateParamsWithTimeout creates a new APIServiceAuthenticateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIServiceAuthenticateParamsWithTimeout(timeout time.Duration) *APIServiceAuthenticateParams {

	return &APIServiceAuthenticateParams{

		timeout: timeout,
	}
}

// NewAPIServiceAuthenticateParamsWithContext creates a new APIServiceAuthenticateParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIServiceAuthenticateParamsWithContext(ctx context.Context) *APIServiceAuthenticateParams {

	return &APIServiceAuthenticateParams{

		Context: ctx,
	}
}

// NewAPIServiceAuthenticateParamsWithHTTPClient creates a new APIServiceAuthenticateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIServiceAuthenticateParamsWithHTTPClient(client *http.Client) *APIServiceAuthenticateParams {

	return &APIServiceAuthenticateParams{
		HTTPClient: client,
	}
}

/*APIServiceAuthenticateParams contains all the parameters to send to the API endpoint
for the Api service authenticate operation typically these are written to a http.Request
*/
type APIServiceAuthenticateParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api service authenticate params
func (o *APIServiceAuthenticateParams) WithTimeout(timeout time.Duration) *APIServiceAuthenticateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api service authenticate params
func (o *APIServiceAuthenticateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api service authenticate params
func (o *APIServiceAuthenticateParams) WithContext(ctx context.Context) *APIServiceAuthenticateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api service authenticate params
func (o *APIServiceAuthenticateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api service authenticate params
func (o *APIServiceAuthenticateParams) WithHTTPClient(client *http.Client) *APIServiceAuthenticateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api service authenticate params
func (o *APIServiceAuthenticateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *APIServiceAuthenticateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
