// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAPIServiceGetEventParams creates a new APIServiceGetEventParams object
// with the default values initialized.
func NewAPIServiceGetEventParams() *APIServiceGetEventParams {
	var ()
	return &APIServiceGetEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIServiceGetEventParamsWithTimeout creates a new APIServiceGetEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIServiceGetEventParamsWithTimeout(timeout time.Duration) *APIServiceGetEventParams {
	var ()
	return &APIServiceGetEventParams{

		timeout: timeout,
	}
}

// NewAPIServiceGetEventParamsWithContext creates a new APIServiceGetEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIServiceGetEventParamsWithContext(ctx context.Context) *APIServiceGetEventParams {
	var ()
	return &APIServiceGetEventParams{

		Context: ctx,
	}
}

// NewAPIServiceGetEventParamsWithHTTPClient creates a new APIServiceGetEventParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIServiceGetEventParamsWithHTTPClient(client *http.Client) *APIServiceGetEventParams {
	var ()
	return &APIServiceGetEventParams{
		HTTPClient: client,
	}
}

/*APIServiceGetEventParams contains all the parameters to send to the API endpoint
for the Api service get event operation typically these are written to a http.Request
*/
type APIServiceGetEventParams struct {

	/*EventID*/
	EventID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api service get event params
func (o *APIServiceGetEventParams) WithTimeout(timeout time.Duration) *APIServiceGetEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api service get event params
func (o *APIServiceGetEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api service get event params
func (o *APIServiceGetEventParams) WithContext(ctx context.Context) *APIServiceGetEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api service get event params
func (o *APIServiceGetEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api service get event params
func (o *APIServiceGetEventParams) WithHTTPClient(client *http.Client) *APIServiceGetEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api service get event params
func (o *APIServiceGetEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEventID adds the eventID to the Api service get event params
func (o *APIServiceGetEventParams) WithEventID(eventID string) *APIServiceGetEventParams {
	o.SetEventID(eventID)
	return o
}

// SetEventID adds the eventId to the Api service get event params
func (o *APIServiceGetEventParams) SetEventID(eventID string) {
	o.EventID = eventID
}

// WriteToRequest writes these params to a swagger request
func (o *APIServiceGetEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param eventId
	if err := r.SetPathParam("eventId", o.EventID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
