// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAPIServiceDeleteEventParams creates a new APIServiceDeleteEventParams object
// with the default values initialized.
func NewAPIServiceDeleteEventParams() *APIServiceDeleteEventParams {
	var ()
	return &APIServiceDeleteEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPIServiceDeleteEventParamsWithTimeout creates a new APIServiceDeleteEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPIServiceDeleteEventParamsWithTimeout(timeout time.Duration) *APIServiceDeleteEventParams {
	var ()
	return &APIServiceDeleteEventParams{

		timeout: timeout,
	}
}

// NewAPIServiceDeleteEventParamsWithContext creates a new APIServiceDeleteEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPIServiceDeleteEventParamsWithContext(ctx context.Context) *APIServiceDeleteEventParams {
	var ()
	return &APIServiceDeleteEventParams{

		Context: ctx,
	}
}

// NewAPIServiceDeleteEventParamsWithHTTPClient creates a new APIServiceDeleteEventParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPIServiceDeleteEventParamsWithHTTPClient(client *http.Client) *APIServiceDeleteEventParams {
	var ()
	return &APIServiceDeleteEventParams{
		HTTPClient: client,
	}
}

/*APIServiceDeleteEventParams contains all the parameters to send to the API endpoint
for the Api service delete event operation typically these are written to a http.Request
*/
type APIServiceDeleteEventParams struct {

	/*EventID*/
	EventID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api service delete event params
func (o *APIServiceDeleteEventParams) WithTimeout(timeout time.Duration) *APIServiceDeleteEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api service delete event params
func (o *APIServiceDeleteEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api service delete event params
func (o *APIServiceDeleteEventParams) WithContext(ctx context.Context) *APIServiceDeleteEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api service delete event params
func (o *APIServiceDeleteEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api service delete event params
func (o *APIServiceDeleteEventParams) WithHTTPClient(client *http.Client) *APIServiceDeleteEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api service delete event params
func (o *APIServiceDeleteEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEventID adds the eventID to the Api service delete event params
func (o *APIServiceDeleteEventParams) WithEventID(eventID string) *APIServiceDeleteEventParams {
	o.SetEventID(eventID)
	return o
}

// SetEventID adds the eventId to the Api service delete event params
func (o *APIServiceDeleteEventParams) SetEventID(eventID string) {
	o.EventID = eventID
}

// WriteToRequest writes these params to a swagger request
func (o *APIServiceDeleteEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param eventId
	if err := r.SetPathParam("eventId", o.EventID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
