// Code generated by go-swagger; DO NOT EDIT.

package api_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/arykalin/kogda-sobitie-backend/pkg/server/v1/grpc/clients/models"
)

// APIServiceAuthenticateReader is a Reader for the APIServiceAuthenticate structure.
type APIServiceAuthenticateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIServiceAuthenticateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAPIServiceAuthenticateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAPIServiceAuthenticateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAPIServiceAuthenticateOK creates a APIServiceAuthenticateOK with default headers values
func NewAPIServiceAuthenticateOK() *APIServiceAuthenticateOK {
	return &APIServiceAuthenticateOK{}
}

/*APIServiceAuthenticateOK handles this case with default header values.

A successful response.
*/
type APIServiceAuthenticateOK struct {
	Payload *models.GrpcAuthenticateResponse
}

func (o *APIServiceAuthenticateOK) Error() string {
	return fmt.Sprintf("[POST /authenticate][%d] apiServiceAuthenticateOK  %+v", 200, o.Payload)
}

func (o *APIServiceAuthenticateOK) GetPayload() *models.GrpcAuthenticateResponse {
	return o.Payload
}

func (o *APIServiceAuthenticateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GrpcAuthenticateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIServiceAuthenticateDefault creates a APIServiceAuthenticateDefault with default headers values
func NewAPIServiceAuthenticateDefault(code int) *APIServiceAuthenticateDefault {
	return &APIServiceAuthenticateDefault{
		_statusCode: code,
	}
}

/*APIServiceAuthenticateDefault handles this case with default header values.

An unexpected error response.
*/
type APIServiceAuthenticateDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the Api service authenticate default response
func (o *APIServiceAuthenticateDefault) Code() int {
	return o._statusCode
}

func (o *APIServiceAuthenticateDefault) Error() string {
	return fmt.Sprintf("[POST /authenticate][%d] ApiService_Authenticate default  %+v", o._statusCode, o.Payload)
}

func (o *APIServiceAuthenticateDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *APIServiceAuthenticateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
