// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GrpcAuthenticateRequest grpc authenticate request
//
// swagger:model grpcAuthenticateRequest
type GrpcAuthenticateRequest struct {

	// id token
	IDToken string `json:"id_token,omitempty"`

	// login
	Login string `json:"login,omitempty"`

	// password
	Password string `json:"password,omitempty"`
}

// Validate validates this grpc authenticate request
func (m *GrpcAuthenticateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GrpcAuthenticateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GrpcAuthenticateRequest) UnmarshalBinary(b []byte) error {
	var res GrpcAuthenticateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
