// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GrpcEvent grpc event
//
// swagger:model grpcEvent
type GrpcEvent struct {

	// amount
	Amount string `json:"amount,omitempty"`

	// date
	Date string `json:"date,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// duration
	Duration string `json:"duration,omitempty"`

	// link
	Link string `json:"link,omitempty"`

	// org
	Org string `json:"org,omitempty"`

	// place
	Place string `json:"place,omitempty"`

	// target
	Target string `json:"target,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// where
	Where string `json:"where,omitempty"`
}

// Validate validates this grpc event
func (m *GrpcEvent) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GrpcEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GrpcEvent) UnmarshalBinary(b []byte) error {
	var res GrpcEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
